name: Build

on:
  workflow_call:
    inputs:
      runSonar:
          required: false
          type: boolean
          default: true

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: running on ${{ github.ref_name }}
        run: echo 'hello, world'

      - name: run runSonar
        if: inputs.runSonar
        run: echo 'hello, world'
        
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
          repository: ${{ github.repository }}
        env:
          token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: "5.x"

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          useConfigFile: true

      - name: apply version
        run: |
          sed -i 's/"version": ".*",/"version": "${{ env.GITVERSION_SEMVER }}",/' app/package.json
          cat app/package.json

      - name: Commit version change
        if: github.ref == 'refs/heads/main'
        run: |
          git config --global user.name 'Dan Cook'
          git config --global user.email '93783090+dancook-socialive@users.noreply.github.com'
          git commit -am "[skip ci] Increment version to ${{ env.GITVERSION_SEMVER }}"
          git push

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: package
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: |
            ./app
