name: Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3
        with:
          git-push: false
          output-file: './app/CHANGELOG.md'
          version-file: './app/package.json'
          skip-commit: true

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: package
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: |
            ./app
