name: Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: apply version
      env:
        SEMVER: ${{ needs.version.outputs.semVer }}
      run: |
        sed -i 's/"version": ".*",/"version": "${{ env.SEMVER }}",/' app/package.json
        cat app/package.json

      # - name: Commit version change
      #   run: |
      #     git config --global user.name 'Dan on a Pipe'
      #     git config --global user.email 'dancook-socialive@users.noreply.github.com'
      #     git commit -am "Increment version"
      #     git push

    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'yarn'

    - name: Install dependencies
      run: yarn install

    - name: Build
      run: yarn build

    - name: package
      uses: actions/upload-artifact@v2
      with:
        name: package
        path: |
          ./app
