name: Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          git-message: 'chore(release): {version}'
          git-user-name: 'Dan in a Pipe'
          git-user-email: 'dancook-socialive@github.actions.com'
          preset: 'angular'
          tag-prefix: 'v'

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: package
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: |
            ./app
