name: Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: "5.x"

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          useConfigFile: true

      - name: apply version
        run: |
          sed -i 's/"version": ".*",/"version": "${{ env.GITVERSION_SEMVER }}",/' app/package.json
          cat app/package.json

      # - name: Commit version change
      #   if: github.ref == 'refs/heads/main'
      #   run: |
      #     git config --global user.name 'Dan on a Pipe'
      #     git config --global user.email 'dancook-socialive@users.noreply.github.com'
      #     git commit -am "Increment version to ${{ env.GITVERSION_SEMVER }} [no ci]"
      #     git push

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: package
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: |
            ./app
