name: CI

on:
  push:
      branches:
        - main
      tags:
        - 'release/**'
  pull_request:
    types: [ closed, opened, synchronize, reopened ]

jobs:
  build:
    uses: ./.github/workflows/build.yml
