name: CI

on:
  push:
      branches:
        - main
      tags:
        - '**'
  pull_request:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      runSonar: ${{ (!startsWith(github.ref, 'refs/tags/release')) }}
