name: Manual Run

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: string
        required: true

jobs:
  build:
    uses: ./.github/workflows/build.yml

