name: Manual Run

on:
  workflow_dispatch:

jobs:
  build:
    if: (!startsWith(github.ref, 'refs/tags/release'))
    runs-on: ubuntu-latest
    steps:
      - run: echo "not a release tag"

  build-prod:
    if: startsWith(github.ref, 'refs/tags/release')
    runs-on: ubuntu-latest
    steps:
      - run: echo "it's a release tag"
