name: Manual Run '(${{ github.ref_name }})' > '(${{ github.event.inputs.environment }})''

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: string
        required: true

jobs:
  build:
    uses: ./.github/workflows/build.yml

